#pragma once

// Default keybindings
enum DefaultKeybind {
	DEFAULT_NONE = GLFW_KEY_UNKNOWN, /*-1*/
	DEFAULT_LOAD_MESH_MODEL = GLFW_KEY_INSERT, /*INSERT*/
	DEFAULT_MOUSE_LOOK = GLFW_KEY_F, /*'f'*/
	DEFAULT_CAM_LEFT = GLFW_KEY_A, /*'a'*/
	DEFAULT_CAM_RIGHT = GLFW_KEY_D, /*'d'*/
	DEFAULT_CAM_FORWARD = GLFW_KEY_W, /*'w'*/
	DEFAULT_CAM_BACKWARD = GLFW_KEY_S, /*'s'*/
	DEFAULT_CAM_UP = GLFW_KEY_SPACE, /*' '*/
	DEFAULT_CAM_DOWN = GLFW_KEY_LEFT_SHIFT, /*SHIFT*/
	DEFAULT_BOUNDING_BOX = GLFW_KEY_B, /*'b'*/
	DEFAULT_VERTEX_NORMALS = GLFW_KEY_N, /*'n'*/
	DEFAULT_WORLD_AXES = GLFW_KEY_X, /*'x'*/
	DEFAULT_RESET_SCENE = GLFW_KEY_R, /*'r'*/
	DEFAULT_OBJECT_AXES = GLFW_KEY_U, /*'u'*/
	DEFAULT_VIEW_OBJECT = GLFW_KEY_V, /*'v'*/
	DEFAULT_OBJ_LEFT = GLFW_KEY_LEFT, /*LEFT*/
	DEFAULT_OBJ_RIGHT = GLFW_KEY_RIGHT, /*RIGHT*/
	DEFAULT_OBJ_FORWARD = GLFW_KEY_UP, /*UP*/
	DEFAULT_OBJ_BACKWARD = GLFW_KEY_DOWN, /*DOWN*/
	DEFAULT_OBJ_UP = GLFW_KEY_PAGE_UP, /*PAGE_UP*/
	DEFAULT_OBJ_DOWN = GLFW_KEY_PAGE_DOWN, /*PAGE_DOWN*/
	DEFAULT_OBJ_SCALE_INC = GLFW_KEY_EQUAL, /*'+'*/
	DEFAULT_OBJ_SCALE_DEC = GLFW_KEY_MINUS, /*'-'*/
	DEFAULT_OBJ_ROTATE = GLFW_MOUSE_BUTTON_RIGHT, /*MOUSE_BUTTON_RIGHT*/
	DEFAULT_PROJECTION_TOGGLE = GLFW_KEY_P, /*'p'*/
	DEFAULT_FPS_CAMERA = GLFW_KEY_G, /*'g'*/
	DEFAULT_OBJ_ALT_MOVE = GLFW_KEY_LEFT_ALT, /*ALT*/
	DEFAULT_ESCAPE_ALL = GLFW_KEY_ESCAPE, /*ESC*/
	DEFAULT_OBJ_CONTROL_MODEL = GLFW_KEY_LEFT_CONTROL, /*CTRL*/
};